### ISSUE TITLE
In some cases, after logging in, the browser window can't not close itself

### ISSUE THREAD

**Issue by mapleeit** [jina-ai/hubble-client-python#40]
Reproduced in: 

- Mac OS safari
- Linux Firefox

I suspect if it's doable. If it's impossible because of security reason, the sentences should be modified accordingly.

**Comment by nomagick** [comment]
Edit text message if automatic window.close is not achiveable

**Comment by floralatin** [comment]
### In some cases, after logging in, the browser window can't not close itself [#40](https://github.com/jina-ai/hubble-client-python/issues/40)
### Info：
Reproduced in: Mac OS safari, Linux Firefox, Mac Chrome
From [MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/Window/close) about window.close()
### Background:
In safari : Can't close the window since it was not opened by JavaScript.
In chrome : Scripts may close only the windows that were opened by them.
In firefox: 脚本不得关闭非脚本打开的窗口。
In edge: Scripts may close only the windows that were opened by them.
### Target: 
Hack the close event
### Solution:
We can use vue to simulate keyboard events and use different systems and different browsers to close the tab hotkey to close the current tab

### My opinion is:
Try it
