### ISSUE TITLE
Login fails in jupyter notebooks

### ISSUE THREAD

**Issue by jupyterjazz** [jina-ai/hubble-client-python#42]
![hubblebug](https://user-images.githubusercontent.com/45267439/170977391-b9ad0ea2-a9e6-4e7f-87c5-fadfb8e73464.png)

I think it's important to support jupyter notebooks, especially for finetuner-client which depends on hubble-client.

**Comment by bwanglzu** [comment]
@nomagick i raised a quick fix, please review.

**Comment by mapleeit** [comment]
This problem comes again once we decided to remove `nest_asyncio` 

https://github.com/jina-ai/hubble-client-python/pull/49

In Google Colab, it doesn't work. @deepankarm suggest we should learn [how jina solves this problem](https://github.com/jina-ai/jina/blob/38e8f2f2b61ea4f080cb924138caea88fcedebb3/jina/helper.py#L1271-L1323).
